# Generated by Django 5.1.5 on 2025-01-25 17:12

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "funicular_up",
            "0002_alter_folder_options_folder_date_folder_description_and_more",
        ),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Caption"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UP", "Uploaded")],
                        default="UP",
                        editable=False,
                        max_length=2,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="funicular_up.folder",
                        verbose_name="Folder",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entry_image",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
    ]
