# Generated by Django 5.1.5 on 2025-03-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funicular_up", "0003_entry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="position",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="entry",
            name="status",
            field=models.CharField(
                choices=[
                    ("UP", "Uploaded to server"),
                    ("DW", "Downloaded to local"),
                    ("RQ", "Requested on server"),
                    ("ST", "Restored from local"),
                    ("KI", "Kill on server"),
                ],
                default="UP",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="YYYY-mm-dd format",
                null=True,
                verbose_name="Date",
            ),
        ),
    ]
